spring:
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/demoshop
      database: demoshop
  datasource:
    url: jdbc:postgresql://localhost:5432/demoshop
    username: demoshop_user
    password: demoshop_pass
    jpa:
      hibernate:
        ddl-auto: update   # or validate in production
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Optional: define queues
  coupon:
    queue:
      name: coupon-events

  order:
    queue:
      name: order-events

  review:
    queue:
      name: review-events