version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  mongo:
    image: mongo:6.0
    container_name: demoshop-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: demoshop
    volumes:
      - mongo-data:/data/db
  postgres:
    image: postgres:15
    container_name: demoshop_postgres
    restart: always
    environment:
      POSTGRES_DB: demoshop
      POSTGRES_USER: demoshop_user
      POSTGRES_PASSWORD: demoshop_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: demoshop_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@demoshop.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  mongo-data:
  postgres_data: